export const portfolio = {
    logos: [
        "OmerAyal.mp4",
        "Maor.mp4",
        "Jonjon.mp4",
        "Dror.mp4",
        "Basement.mp4",
        "BM.mp4",
        "CM.webp",
        "ForsetCafe.webp",
        "Irina.webp",
        "EA.webp",
        "Global.webp",
        "Liav.webp",
        "YuviTattoos.webp",
        "AirForBreathing.webp",
        "GiftGromParents.webp",
        "Together.webp",
        "PinkTank.webp",
        "RIG.webp",
        "GotAGirlfriend1.webp",
        "Lion.webp",
        "IronBridge.webp",
        "BederechNes.webp",
        "LaunchDepartment.webp",
        "TheTinker.webp",
        "TheTinker2.webp",
        "Granit.webp",
        "Nevo.webp",
        "Nevo2.webp",
        "Nevo3.webp",
        "Nevo4.webp",
        "Mekashkeshim.webp",
        "Goji.webp",
        "AeroBack.webp",
        "Sahar.webp",
        "Jahnunia.webp",
        "JustBe.webp",
        "iDrift.webp",
        "Hagna.webp"
    ],

    posters: [
        "Ron.webp",
        "StillOutside.webp",
        "6Months.webp",
        "EmptyChair.webp",
        "NoaPoster.webp",
        "HagaiPoster.webp",
        "NoaPoster2.webp",
        "Kozmo.webp",
        "Trigger.webp",
        "High.webp",
        "DancingInParadise.webp",
        "CookBook.webp",
        "Alin.webp",
        "MatanPoster.webp"
    ],

    artworks: [
        "NoaNir.webp",
        "Nigmeret.mp4",
        "Alive.mp4",
        "GotAGirlfriend2.webp",
        "Supernova.webp",
        "Shluliot.webp",
        "Honest.webp",
        "FollowMeHome2.webp",
        "BeautifulWorld2.webp",
        "LeftAlone.webp",
        "DoNotSee3.webp",
        "Mantra.webp",
        "BeautifulWorld.webp",
        "ShirHaaval.webp",
        "Wings.webp",
        "MyMonster.webp",
        "FollowMeHome.webp",
        "ImHere.webp",
        "DoNotSee.webp",
        "BeautifulWorld3.webp",
        "Shluliot2.webp",
        "NoasSong.webp",
        "OpenedMyHeart.webp",
        "360.webp",
        "Flower.webp",
        "AtTheEndOfEachDay.webp",
        "ZeAsur.webp",
        "AllWeWere.webp",
        "LeftAlone2.webp",
        "DoNotSee2.webp",
        "GotAGirlfriend3.webp",
        "OmesYeter.webp",
        "KeshevVerikuz.webp",
        "Stress.webp",
        "RoomFullOfMirrors.webp",
        "RoomFullOfMirrors2.webp",
        "360_2.webp",
        "Lechaim.webp",
        "360Back.webp",
        "Kama.webp",
        "ZhutHashtika.webp",
        "TipotShelTal.webp",
        "Vaashuva.webp",
        "UntilTheLight.webp",
        "TryAgain.webp",
        "Pitom.webp",
        "Bdidut.webp",
        "Pilpel.webp",
        "Hadarom.webp",
        "HadvashHaze.webp",
        "Steve.webp"
    ],

    videos: [{
            title: "נעה ניר - מאז שהרגשתי",
            youtubeId: "dKTIxhjpfP4"
        },
        {
            title: "חגי בר מאיר - שלוליות",
            youtubeId: "ajFa4UNsTm0"
        },
        {
            title: "דניאל ברזילאי - האור ואושרי",
            youtubeId: "hK749tcuLTc"
        },
        {
            title: "חגו - אלך איתך",
            youtubeId: "c2iYZr-xYs8"
        },
        {
            title: "נעה שאואט - מי כותב לי תתסריט",
            youtubeId: "FokyoOjJPaA"
        },
         {
            title: "נעה ניר - שיר לנועה",
            youtubeId: "gzLiI4ZQeCI"
        }
    ]
};
